/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Waecm01CookieBanner {
        "link": string;
        "name": string;
    }
}
declare global {
    interface HTMLWaecm01CookieBannerElement extends Components.Waecm01CookieBanner, HTMLStencilElement {
    }
    var HTMLWaecm01CookieBannerElement: {
        prototype: HTMLWaecm01CookieBannerElement;
        new (): HTMLWaecm01CookieBannerElement;
    };
    interface HTMLElementTagNameMap {
        "waecm01-cookie-banner": HTMLWaecm01CookieBannerElement;
    }
}
declare namespace LocalJSX {
    interface Waecm01CookieBanner {
        "link"?: string;
        "name"?: string;
        "onOn-accept"?: (event: CustomEvent<string[]>) => void;
    }
    interface IntrinsicElements {
        "waecm01-cookie-banner": Waecm01CookieBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "waecm01-cookie-banner": LocalJSX.Waecm01CookieBanner & JSXBase.HTMLAttributes<HTMLWaecm01CookieBannerElement>;
        }
    }
}
